Добавление дополнительной абстракции для работы с бд #128
MoreliaTalk/morelia_server pull request #136
Opened 2021-12-06 21:21 UTC by stepanskryabin

Во имя DRY добавлен класс DBHandler для удобной работы с БД (чтобы не подключать в каждом месте БД и не писать запросы). Написаны тесты для его тестирования, и сразу имплементированы все изменения в код сервера.

2021-12-07 13:52 UTC, NekrodNIK requested changes
В целом нормально, претензии больше к изменённому форматированию кода, что изначально писал я.

2021-12-07 13:52 UTC, NekrodNIK commented on admin/admin.py
> +                                       "users": dbquery.count()})
Тут тоже

2021-12-07 13:52 UTC, NekrodNIK commented on admin/admin.py
> +                                      {"request": request})
Тут придираться не буду, т.к. ключ в словаре один, и тут нужно делать именно так.

2021-12-07 13:52 UTC, NekrodNIK commented on admin/login.py
> +                             use_header=False)
В функциях тоже хочется придраться, но... тут это смотрится даже хорошо

2021-12-07 13:52 UTC, NekrodNIK commented on admin/login.py
> +                             incorrect_token)
ЗАЧЕМ? Тут всего 2 коротких аргумента...

2021-12-07 13:52 UTC, NekrodNIK commented on admin/logs.py
> +             user=Depends(login.login_manager)):
Тут да, оправдано, т.к. именованный аргумент

2021-12-07 13:52 UTC, NekrodNIK commented on mod/db/dbhandler.py
> +            dbquery.salt = salt
Мои глаза... Так это и хочется заменить чем-нибудь... Может в начале функции получить список её переменных(а в самом начале он равен списку его аргументов)? Хотя нет, я чего-то не доверяю vars()...

2021-12-07 13:52 UTC, NekrodNIK commented on setup.cfg
>  max-line-lenght = 79
Гитхаб ненавязчиво намекает, что файл не оканчивается пустой строкой

2021-12-07 13:52 UTC, NekrodNIK commented on tests/fixtures/auth.json
> +    "type": "authentification",
Ну... А разница?

2021-12-07 13:52 UTC, NekrodNIK commented on tests/fixtures/ping_pong.json
> +    "type": "ping_pong",
А тут правильно, нам кебаб стайл ни к чему.

2021-12-07 16:13 UTC, stepanskryabin commented on admin/login.py
> +                             incorrect_token)
чтобы везде было единообразие

2021-12-07 16:15 UTC, stepanskryabin commented on mod/db/dbhandler.py
> +            dbquery.salt = salt
Если только через цикл с проверкой на True..

2021-12-07 16:16 UTC, stepanskryabin commented on setup.cfg
>  max-line-lenght = 79
поправил

2021-12-07 16:18 UTC, stepanskryabin commented on tests/fixtures/auth.json
> +    "type": "authentification",
правильное наименование методов, чтобы везде нейминг был одинаковый

2021-12-08 04:17 UTC, NekrodNIK commented on mod/db/dbhandler.py
> +            dbquery.salt = salt
Может быть... Хотя лучше не надо так делать...

2021-12-08 04:19 UTC, NekrodNIK commented on tests/fixtures/ping_pong.json
> +    "type": "ping_pong",
Да, дикие шашлычники с гор Кавказа постарались. В наш змеиный стиль проникли)))

2021-12-08 06:02 UTC, stepanskryabin commented on mod/db/dbhandler.py
> +            dbquery.salt = salt
не, через цикл тоже не получится, надо чтобы имена объёктов совпадали с именем поля в БД

2021-12-08 06:10 UTC, stepanskryabin commented on admin/admin.py
> +                                       "users": dbquery.count()})
исправил

2021-12-08 06:11 UTC, stepanskryabin commented on mod/db/dbhandler.py
> +            dbquery.salt = salt
оставляем как есть?

2021-12-08 08:53 UTC, NekrodNIK commented on mod/db/dbhandler.py
> +            dbquery.salt = salt
Да, оставляем как есть.

2021-12-08 08:55 UTC, NekrodNIK approved these changes

2021-12-10 03:15 UTC, NekrodNIK approved these changes

2021-12-10 19:37 UTC, rus-ai commented on mod/db/dbhandler.py
> +            dbquery.salt = salt
Может так?
```
dbquery.bio = bio if bio
dbquery.key = key if key
и так далее
```
Или если выпендриваться:
```
for var in ('login;, 'password', 'username', 'bio', 'key', 'avatar', и т.д. ):
     dbquery.[var] = vars().[var] if vars().[var]
```

2021-12-10 19:42 UTC, rus-ai commented on Pipfile
> +win32-setctime = "*"
Что не нашел, а мы это используем? А в Линуксе как?

2021-12-10 19:56 UTC, rus-ai commented on mod/controller.py
> +        dbquery_message = self._db.get_message_by_more_time(request.data.time)
more_time как то тут не к месту, я бы назвал after_time

2021-12-10 20:07 UTC, rus-ai commented on mod/db/dbhandler.py
> +    def create(self) -> None:
Ты зачем то документировал что функция возвращает None, а сам потом возвращаешь строку `return "Ok"`

И дальше по коду в следующих методах аналогично

2021-12-10 20:11 UTC, rus-ai requested changes
Оставил комментарии по тексту, из критичного только несоответствие объявлению функции и возвращаемого типа.

2021-12-11 06:07 UTC, stepanskryabin commented on Pipfile
> +win32-setctime = "*"
этот пакет в зависимостях у loguru, используется в винде

2021-12-11 06:09 UTC, stepanskryabin commented on mod/controller.py
> +        dbquery_message = self._db.get_message_by_more_time(request.data.time)
Согласен, неймин не очень хороший у меня получился. Я пытался написать три одинаковые метода, для запроса сообщений до временной метки, равно ременной метки и более временной метки. Попробую по твоему варианту сделать.

2021-12-11 06:17 UTC, stepanskryabin commented on mod/db/dbhandler.py
> +    def create(self) -> None:
Да, когда отлаживал код добавил 'Ok'. Потом забыл убрать.

2021-12-11 17:42 UTC, stepanskryabin commented on mod/db/dbhandler.py
> +            dbquery.salt = salt
Я сейчас внимательно прочитал твой код и нифига не понял. Мне кажется проще так:
```python
for var in ('login', 'password', 'username', 'bio', 'key', 'avatar', и т.д. ):
    if var:
        setattr(dbquery, 'var', var)
```

2021-12-11 17:46 UTC, stepanskryabin commented on mod/controller.py
> +        dbquery_message = self._db.get_message_by_more_time(request.data.time)
думаю вариант с 'after' не сильно лучше моего с 'more'. After это после, а у меня функция выдаёт результат при условии что время сообщения больше времени переданном в параметрах этой функции. Нужен вариант получше.

2021-12-11 17:49 UTC, stepanskryabin commented on mod/db/dbhandler.py
> +    def create(self) -> None:
исправил

2021-12-11 18:10 UTC, rus-ai submitted a review, later dismissed

2021-12-13 18:52 UTC, rus-ai approved these changes

2021-12-14 10:45 UTC, NekrodNIK approved these changes

2021-12-14 15:24 UTC, merged