Разделение кода протокола и контроллера #139
MoreliaTalk/morelia_server pull request #141
Opened 2021-12-25 19:44 UTC by stepanskryabin

Код протокола перенесён в модуль mtp который находится в директории mod/protocol.
Добавлен модуль-заглушка для протокола matrix.
Добавлены/исправлены тесты для controller.py и модуля mtp.

Мелкие правки не по тикету #139 

- удалено чтение config.ini для присвоения URI в случаях когда в объект DBHandler не передается URI базы данных.
- в случае если в DBHandler не передать URI будет использована БД размещаемая в памяти
- функция check_error_pattern() (из error.py) теперь возвращает не Enum а именованный кортеж с параметрами: code, status, detail

2021-12-26 04:51 UTC, stepanskryabin commented on mod/db/dbhandler.py
> +                 uri: str = None,
да, ты прав. так и сделаю.

2021-12-26 05:24 UTC, stepanskryabin commented on mod/error.py
>              obj = getattr(ServerStatus, status)
Если конструкция в try не срабатывает то у нас райзится АтрибутЕррор, и в таком случае obj никто не использует и за ним идёт сборщик мусора, мне стало жалко этот obj (:smile: ) А если серьёзно, то я решил исправить чтобы от меня отвязался PyCharm.

2021-12-26 11:34 UTC, rus-ai approved these changes

2021-12-30 11:15 UTC, NekrodNIK requested changes
Как обычно, в основном придраться не к чему, однако же пару мелочей всё же найти можно

2021-12-30 11:15 UTC, NekrodNIK commented on mod/controller.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Зачем изменил дату? Написано же с 2020 по настоящее время, менять на 2021 нельзя, так как часть кода была написана в 2020)))

2021-12-30 11:15 UTC, NekrodNIK commented on mod/controller.py
> +            self.response = self.mtp_handler()
Ну не знаю... Лучше сделать так:
```python
if protocol == "mtp":
   self.response = self.mtp_handler()
elif protocol == "matrix":
   self.response = self.matrix_handler()
else:
   # возвращаем ошибку, дескать неизвестный протокол

2021-12-30 11:15 UTC, NekrodNIK commented on mod/error.py
>              obj = getattr(ServerStatus, status)
Вот что с людьми PyCharm делает)))

2021-12-30 11:15 UTC, NekrodNIK commented on mod/protocol/__init__.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Опять 2021...

2021-12-30 11:15 UTC, NekrodNIK commented on mod/protocol/matrix/__init__.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
И тут тоже

2021-12-30 11:15 UTC, NekrodNIK commented on mod/protocol/matrix/api.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
...

2021-12-30 11:15 UTC, NekrodNIK commented on mod/protocol/matrix/worker.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Я конечно понимаю, что конкретно эта часть была создана в этом году... но вот куда лучше оставить 2020

2021-12-30 11:15 UTC, NekrodNIK commented on mod/protocol/mtp/__init__.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
...

2021-12-30 11:15 UTC, NekrodNIK commented on mod/protocol/mtp/worker.py
> +    Copyright (c) 2020 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ура, тут хотя бы 2020 год!

2021-12-30 11:15 UTC, NekrodNIK commented on tests/test_controller.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
2021, ну когда ты нас отпустишь! А, через день уже...

2021-12-30 11:19 UTC, stepanskryabin commented on mod/controller.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Тут код кардинально поменялся (старыц мепеместил в protocol/mtp/worker.py), по этому поменял дату.

2021-12-30 11:22 UTC, stepanskryabin commented on mod/controller.py
> +            self.response = self.mtp_handler()
Такой вариант - это первое что пришло в голову, но потом вопрос возник: "а каким протоколом возвращать ошибку и зачем столько лишнего кода?". Короче проще проверять пока на "matrix" и если не он то использовать mtp чем ещё и пилить сюда код возврата ошибки. Keep it simple, stupid!

2021-12-30 11:22 UTC, stepanskryabin commented on mod/protocol/__init__.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну новый же код, как я 2020 год поставлю?

2021-12-30 11:22 UTC, stepanskryabin commented on mod/protocol/matrix/__init__.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну новый же код, как я 2020 год поставлю?

2021-12-30 11:22 UTC, stepanskryabin commented on mod/protocol/matrix/api.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну новый же код, как я 2020 год поставлю?

2021-12-30 11:22 UTC, stepanskryabin commented on mod/protocol/matrix/worker.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну новый же код, как я 2020 год поставлю?

2021-12-30 11:22 UTC, stepanskryabin commented on mod/protocol/mtp/__init__.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну новый же код, как я 2020 год поставлю?

2021-12-30 11:23 UTC, stepanskryabin commented on mod/protocol/mtp/worker.py
> +    Copyright (c) 2020 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
это старый код, конечно тут год сохранился

2021-12-30 11:23 UTC, stepanskryabin commented on tests/test_controller.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну новый же код, как я 2020 год поставлю?

2021-12-30 11:47 UTC, NekrodNIK commented on mod/controller.py
> +            self.response = self.mtp_handler()
Ну выглядит, как будто мы тут во главу всего ставим matrix, так и ещё в случае если к нам обращаются с неизвестным протоколом - посылаем в mtp, дескать там разберутся))) А в итоге клиент даже не поймёт, что не с тем протоколом к нам зашёл

2021-12-30 11:48 UTC, NekrodNIK commented on mod/controller.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Но права то нам на него пренадлежат с какого времени? правильно с 2020

2021-12-30 11:49 UTC, NekrodNIK commented on mod/protocol/__init__.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну ладно, просто путаницу вносит в копирайты.

2021-12-30 11:49 UTC, NekrodNIK commented on mod/protocol/matrix/__init__.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну ладно, просто путаницу вносит в копирайты.

2021-12-30 11:50 UTC, NekrodNIK commented on mod/protocol/matrix/api.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну ладно, просто путаницу вносит в копирайты(петля времени продолжается)

2021-12-30 11:50 UTC, NekrodNIK commented on mod/protocol/matrix/worker.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну ладно, просто путаницу вносит в копирайты.

2021-12-30 11:50 UTC, NekrodNIK commented on mod/protocol/mtp/__init__.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ну ладно, просто путаницу вносит в копирайты.

2021-12-30 11:57 UTC, NekrodNIK commented on tests/test_controller.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
С Новым Кодом!

2021-12-30 12:00 UTC, stepanskryabin commented on mod/controller.py
> +            self.response = self.mtp_handler()
у нас пока один протокол, зачем усложнят ь логику раньше времени? я стараюсь идти по пути наименьньших изменений.

2021-12-30 12:10 UTC, stepanskryabin commented on mod/controller.py
> +    Copyright (c) 2021 - present NekrodNIK, Stepan Skriabin, rus-ai and other.
Ладно, уговорил.

2021-12-30 12:13 UTC, NekrodNIK commented on mod/controller.py
> +            self.response = self.mtp_handler()
ладно, пофиг

2021-12-30 12:18 UTC, NekrodNIK approved these changes

2021-12-30 12:20 UTC, merged