Реализованы автотестирование и автосборка проекта, а также исправлен ряд багов. #45 #97 #147 #148 #149 #153 #158
MoreliaTalk/morelia_server pull request #161
Opened 2022-02-01 12:46 UTC by NekrodNIK

Список изменений:
- добавлено автотестирование и автолинтинг проекта с помощью github actions
- добавлен вывод данных о покрытии кода тестами, с помощью сервиса [coveralls.io](https://coveralls.io)
- добавлена автосборка проекта в изображение docker, а также его автопубликация на github packages
- добавлена автосборка и автопубликация документации по проекту
- исправлен баг #147
- исправлен баг #148 
- исправлен баг #149 
- добавлены тесты для server.py

2022-02-01 14:36 UTC, stepanskryabin commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/MoreliaTalk/morelia_server/badge.svg?branch=develop-nekrod)](https://coveralls.io/github/MoreliaTalk/morelia_server)
Такие же строчки нужно обязательно вставить в англоязычный Ридми.

2022-02-01 14:38 UTC, stepanskryabin commented on tests/test_protocol_mtp_worker.py
> +url_db = "sqlite:/:memory:?debug=1"
и вместо URL_DB может просто DATABASE?

2022-02-01 16:14 UTC, stepanskryabin commented
Вроде как баг #147 так и не исправлен, как м инимум кода я не вижу.
И по багу #149 исправлено не до конца, т.к. не исправлена вот эта ошибка:

> Если клиент вообще не укажет UUID пользователей, то сервер отвечает кодом 520 "UNKNOWN_ERROR" вместо кода 400 "Bad Request"

2022-02-01 16:20 UTC, stepanskryabin commented on tests/test_server.py
> +from json import JSONDecodeError
Импортируется JSONDecoder но почему-то нигде не используется?

2022-02-01 16:21 UTC, stepanskryabin commented on tests/test_server.py
> +
добавь в тесты глобальное отключение логгера

2022-02-01 16:29 UTC, stepanskryabin commented on tests/test_server.py
> +            connection.close()
Я не совсем понял что здесь происходит!? Строки 20, 24, 28, 32
В 32 строке так совсем райзится `json.decoder.JSONDecodeError`, но это никак не отлавливается в тесте и не понятно зачем это всё?

2022-02-01 16:30 UTC, NekrodNIK commented on Pipfile
> +bpython = "*"
Так на то это и dev-зависимость, что в проекте не используется. А для разработки штука полезная

2022-02-01 16:31 UTC, NekrodNIK commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/MoreliaTalk/morelia_server/badge.svg?branch=develop-nekrod)](https://coveralls.io/github/MoreliaTalk/morelia_server)
Да, поправлю

2022-02-01 16:31 UTC, stepanskryabin requested changes
В основном всё класс, но необходимо внести пару правок.

2022-02-01 16:31 UTC, NekrodNIK commented on tests/test_protocol_mtp_worker.py
> +url_db = "sqlite:/:memory:?debug=1"
Возможно

2022-02-01 16:32 UTC, NekrodNIK commented
> Вроде как баг #147 так и не исправлен, как минимум кода я не вижу.
> И по багу #149 исправлено не до конца, т.к. не исправлена вот эта ошибка:
> 
> > Если клиент вообще не укажет UUID пользователей, то сервер отвечает кодом 520 "UNKNOWN_ERROR" вместо кода 400 "Bad Request"

Баг #147 я как ни тестировал, но однако не выявил, значит его нету. А по багу #149 видимо не заметил, поправлю

2022-02-01 16:33 UTC, NekrodNIK commented on tests/test_server.py
> +
Ладно

2022-02-01 16:35 UTC, stepanskryabin commented on mod/protocol/mtp/worker.py
> +                flow.append(api.FlowResponse(uuid=flow_uuid))
Пожелание: можно добавить в тесты проверку отправил ли сервер message_start и message_end в ответе (при MESSAGE_COUNT <= LIMIT)

2022-02-01 16:36 UTC, NekrodNIK commented on tests/test_server.py
> +            connection.close()
Просто написал больше тестов, и всë. Ладно, заодно их переработаю

2022-02-01 16:38 UTC, NekrodNIK commented on mod/protocol/mtp/worker.py
> +                flow.append(api.FlowResponse(uuid=flow_uuid))
Ладно, в список правок занесу

2022-02-01 16:38 UTC, stepanskryabin commented on Pipfile
> +bpython = "*"
bpython не относится к необходимым инструментам разработки, без него всё нормально можно делать.

2022-02-01 16:40 UTC, stepanskryabin commented on tests/test_server.py
> +            connection.close()
там просто ассерт бы какой ни буть вставить из юниттеста, вот в тест где райзится json.decoder.JSONDecodeError надо её и отловить, и всё будет замечательно.

2022-02-01 16:42 UTC, NekrodNIK commented on Pipfile
> +bpython = "*"
Но удобней на коленке тестировать)))

2022-02-01 16:42 UTC, stepanskryabin commented
> > Вроде как баг #147 так и не исправлен, как минимум кода я не вижу.
> > И по багу #149 исправлено не до конца, т.к. не исправлена вот эта ошибка:
> > > Если клиент вообще не укажет UUID пользователей, то сервер отвечает кодом 520 "UNKNOWN_ERROR" вместо кода 400 "Bad Request"
> 
> Баг #147 я как ни тестировал, но однако не выявил, значит его нету. А по багу #149 видимо не заметил, поправлю

Да я вот тоже не нашел в чём проблема, вроде по коду всё нормально выдаёт. Короче считаем исправленным, но если всплывёт в очередной раз, то я тикет переоткрою.

2022-02-01 16:45 UTC, NekrodNIK commented
> > > Вроде как баг #147 так и не исправлен, как минимум кода я не вижу.
> > > И по багу #149 исправлено не до конца, т.к. не исправлена вот эта ошибка:
> > > > Если клиент вообще не укажет UUID пользователей, то сервер отвечает кодом 520 "UNKNOWN_ERROR" вместо кода 400 "Bad Request"
> > 
> > Баг #147 я как ни тестировал, но однако не выявил, значит его нету. А по багу #149 видимо не заметил, поправлю
> 
> Да я вот тоже не нашел в чём проблема, вроде по коду всё нормально выдаёт. Короче считаем исправленным, но если всплывёт в очередной раз, то я тикет переоткрою.

Ок, ладно. Но я сам кучу раз проверял, и так, и сяк, и тулзу для удобства написал - выдаëт, как и надо всë правильно. Так что да - пока закрыли, но если заметим сей баг - то откроем тикет заново

2022-02-01 16:45 UTC, stepanskryabin commented on Pipfile
> +bpython = "*"
а как bpython относится к тестированию? и где bpython дает преимущества по сравнению с пайчармом?

Я знаю что такое bpython и пользуюсь им, и одна из причин моего перехода с Win на Linux было использование нормального bpython, а не полурабочего в windows

2022-02-01 17:14 UTC, NekrodNIK commented on Pipfile
> +bpython = "*"
Я всмылсе, когда надо что-то набросать, а в файл писать не хочется, то куда мы пойдëм? Правильно в интерактивную консоль. А стандартная жутко не удобна. Хотя, конечно, в 90℅ случаев она не нужна, но всë же

2022-02-01 17:18 UTC, stepanskryabin commented on Pipfile
> +bpython = "*"
я пока работал в винде запускал стандартнтую питоновскую IDLE и не пищал ))

2022-02-02 03:39 UTC, NekrodNIK commented on Pipfile
> +bpython = "*"
Ладно, уберу bpython из dev-зависимостей. Всë равно я его раза 2 использовал, да и не сильно он тогда нужен был)))

2022-02-02 04:14 UTC, NekrodNIK commented on Pipfile
> +bpython = "*"
Готово

2022-02-02 04:20 UTC, NekrodNIK commented on tests/test_protocol_mtp_worker.py
> +url_db = "sqlite:/:memory:?debug=1"
Готово

2022-02-02 04:21 UTC, NekrodNIK commented on tests/test_server.py
> +from json import JSONDecodeError
Готово

2022-02-02 05:00 UTC, NekrodNIK commented on tests/test_server.py
> +
Готово

2022-02-02 05:04 UTC, NekrodNIK commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/MoreliaTalk/morelia_server/badge.svg?branch=develop-nekrod)](https://coveralls.io/github/MoreliaTalk/morelia_server)
Готово

2022-02-02 19:42 UTC, stepanskryabin commented on tests/test_server.py
> +if LOGGING.getboolean("UVICORN_LOGGING_DISABLE"):
Логгер необходимо отключать в конкретном тесткейсе, глобально так как ты сделал не работает.

2022-02-02 19:43 UTC, stepanskryabin commented on tests/test_server.py
> +class TestWebsocket(unittest.TestCase):
Тесты не доработаны, смотри документацию starlette, там есть ассерты.

2022-02-02 19:43 UTC, stepanskryabin requested changes
test_server.py необходимо доработать, отсутствует проверка результатов работы экземпляр TestClient(app).
В остальном всё нормально, принимаю.

2022-02-07 09:10 UTC, NekrodNIK commented on tests/test_server.py
> +            connection.close()
нет, не выйдет, ошибка не рейзится, её перехватывает except в server.py и просто выводит в логи. В общем трогать эти тесты я не буду)))

2022-02-07 09:19 UTC, NekrodNIK commented on mod/protocol/mtp/worker.py
> +                flow.append(api.FlowResponse(uuid=flow_uuid))
Готово

2022-02-07 10:41 UTC, NekrodNIK commented on tests/test_server.py
> +if LOGGING.getboolean("UVICORN_LOGGING_DISABLE"):
он так и так отключается, когда подключается server.py. В общем убрал эти строки кода

2022-02-12 12:12 UTC, stepanskryabin requested changes
Исправить генерацию документации в соответствующих *.rst и поправить длинну строк, не выходя за пределы в 79 символов.

2022-02-12 12:12 UTC, stepanskryabin commented on docs/source/conf.py
> +
Ну соответственно после вышеуказанного исправления эта функция не нужна.

2022-02-12 12:12 UTC, stepanskryabin commented on tests/test_server.py
> +            })
Исправь форматирование. Перенос первой строки JSON не делаей, переноси следующие.

Типа того
```javascript
{"type": "ping-pong",
 "data": {"user": [{}]},
 "jsonapi": {"version": "1.0",
                   "revision": "17"},
  "meta": None}
```

2022-02-12 12:12 UTC, stepanskryabin commented on tests/test_server.py
> +                )
Тут тоже намудрил с переносами.

2022-02-12 12:12 UTC, stepanskryabin commented on tests/test_server.py
> +        cls.ws_client = TestClient(app)
добавь уже вырубатель логуру.

2022-02-12 12:14 UTC, stepanskryabin commented on docs/source/conf.py
> +
точнее 81 строка

2022-02-12 12:15 UTC, NekrodNIK commented on admin/admin.py
> +    IGNORE_IN_DOCS:
А что, теперь придётся каждую функцию вручную импортировать? При импортировании как automodule автоматически включается докстринг лицензии, нам он там зачем? А остальное можно после закрывающего тега писать, если нужно

2022-02-12 12:16 UTC, NekrodNIK commented on docs/source/conf.py
> +
.

2022-02-12 12:16 UTC, stepanskryabin commented on admin/admin.py
> +    IGNORE_IN_DOCS:
Дополню: я не прошу дописывать документацию, можешь пока заглушки поставить. Но у документации должна быть возможность расширения и не только за счёт дополнительных описаний в докстрингах.

2022-02-12 12:17 UTC, NekrodNIK commented on tests/test_server.py
> +                )
Осталось от длинной функции, которую потом я убрал

2022-02-12 12:18 UTC, stepanskryabin commented on admin/admin.py
> +    IGNORE_IN_DOCS:
я по этому не стал использовать `automodule` т.кю он тащит всё и с ним сложно расширить документацию без того чтобы не писать в код докстринги.

2022-02-12 12:18 UTC, NekrodNIK commented on admin/admin.py
> +    IGNORE_IN_DOCS:
А как иначе? у меня там нет классов, а каждую функцию по отдельности подключать - ну это бред

2022-02-12 12:19 UTC, stepanskryabin commented on admin/admin.py
> +    IGNORE_IN_DOCS:
Не бред, а работа над адекватной документацией.. и потом если у тебя куча функций про которые нечего сказать может и нафиг они не нужны?

2022-02-12 12:22 UTC, NekrodNIK commented on admin/admin.py
> +    IGNORE_IN_DOCS:
Ну я вообще бы админку переписал, и не факт, что на fastapi, но как есть. То есть ты предлагаешь либо вообще вырубить документацию, либо подключать по одной...

2022-02-12 12:23 UTC, stepanskryabin commented on admin/admin.py
> +    IGNORE_IN_DOCS:
Вот тебе [пример](https://selenium-python.readthedocs.io/api.html#module-selenium.common.exceptions) документации оформленной с использованием `automodule`. После её прочтения хочется уебать разарбов.

2022-02-12 12:24 UTC, stepanskryabin commented on admin/admin.py
> +    IGNORE_IN_DOCS:
> Ну я вообще бы админку переписал, и не факт, что на fastapi, но как есть. То есть ты предлагаешь либо вообще вырубить документацию, либо подключать по одной...

вырубать определённо не нужно, добавь по одной.

2022-02-12 12:24 UTC, NekrodNIK commented on tests/test_server.py
> +            })
Готово

2022-02-12 12:25 UTC, NekrodNIK commented on tests/test_server.py
> +                )
Готово

2022-02-12 12:31 UTC, stepanskryabin commented on tests/test_server.py
> +            })
не до конца)))
надо так:
```javascript
connection.send_json({"type": "ping-pong",
                                     "data": {"user": [{}]},
                                     "jsonapi": {"version": "1.0",
                                                      "revision": "17"},
                                      "meta": None})
```

2022-02-12 12:44 UTC, stepanskryabin commented on tests/test_server.py
> +        cls.ws_client = TestClient(app)
Странно ты как-то его добавил, достаточно в метод `setUpClass` добавить `loguru.remove()`
И до кучи, можно оба тест кейса объеденить в один.

2022-02-12 12:45 UTC, NekrodNIK commented on tests/test_server.py
> +            })
Готово

2022-02-12 12:46 UTC, NekrodNIK commented on admin/admin.py
> +    IGNORE_IN_DOCS:
> Вот тебе [пример](https://selenium-python.readthedocs.io/api.html#module-selenium.common.exceptions) документации оформленной с использованием `automodule`. После её прочтения хочется уебать разарбов.

Твою... Ладно уберу

2022-02-12 12:47 UTC, NekrodNIK commented on tests/test_server.py
> +        cls.ws_client = TestClient(app)
если добавлю в класс, то сообщения будут ровно до запуска тестов. Что как бы не есть гуд. А функцию поправлю

2022-02-12 12:52 UTC, NekrodNIK commented on tests/test_server.py
> +        cls.ws_client = TestClient(app)
Нет, так не катит. remove удалит его уже после появления, то есть наследить тот успевает. А disable недаёт ему работать даже до его появления

2022-02-12 12:52 UTC, NekrodNIK commented on tests/test_server.py
> +        cls.ws_client = TestClient(app)
Короче оставляю как есть, оно работает

2022-02-12 13:05 UTC, NekrodNIK commented on admin/admin.py
> +    IGNORE_IN_DOCS:
Готово

2022-02-12 13:06 UTC, stepanskryabin commented on tests/test_server.py
> +        cls.ws_client = TestClient(app)
ладно.

2022-02-12 13:07 UTC, stepanskryabin commented on docs/source/conf.py
> +from sphinx.ext.autodoc import between
Импорт забыл убрать.

2022-02-12 13:08 UTC, NekrodNIK commented on docs/source/conf.py
> +from sphinx.ext.autodoc import between
Готово

2022-02-12 13:15 UTC, stepanskryabin approved these changes

2022-02-12 13:22 UTC, merged