Добавлена проверка типов
MoreliaTalk/morelia_server pull request #184
Opened 2022-04-16 12:58 UTC by NekrodNIK

Изменения:
- Добавлена проверка типов с помощью mypy в сценарий проверки кода github ci
- Исправлены обнаруженные конфликты типов

Примечание: Обязательная типизация включена не была, в будущем потихоньку будем дописывать тайп-хинтинги, когда закончим - включим

2022-04-17 06:29 UTC, stepanskryabin requested changes
Необходимы небольшие изменения.

2022-04-17 06:29 UTC, stepanskryabin commented on Pipfile
> +mypy = "*"
Перенеси mypy в секцию [dev-packages]

2022-04-17 06:29 UTC, stepanskryabin commented on manage.py
> +from websockets import client as ws_client, exceptions as ws_exceptions
Разбей на две строки.

2022-04-17 06:29 UTC, stepanskryabin commented on mod/config/config.py
> +from typing import Any, Optional, Tuple
Разбей на три строки.

2022-04-17 06:29 UTC, stepanskryabin commented on mod/controller.py
> +            (str):
Убери ":", а то во всплывающей справке не показывает что возвращаетс метод. Да, косяк был мой :smile:

2022-04-17 06:29 UTC, stepanskryabin commented on mod/controller.py
> +            (str):
Тут тоже ":".

2022-04-17 06:29 UTC, stepanskryabin commented on mod/db/dbhandler.py
> +from typing import Any, Optional
Перенеси на две строки.

2022-04-17 06:29 UTC, stepanskryabin commented on mod/protocol/mtp/worker.py
> +from typing import Any, Optional, Union
Перенеси на стри строки.

2022-04-18 17:29 UTC, NekrodNIK commented on Pipfile
> +mypy = "*"
Готово

2022-04-21 10:34 UTC, NekrodNIK commented on manage.py
> +from websockets import client as ws_client, exceptions as ws_exceptions
Готово

2022-04-21 10:36 UTC, NekrodNIK commented on mod/config/config.py
> +from typing import Any, Optional, Tuple
Готово

2022-04-21 10:58 UTC, NekrodNIK commented on mod/controller.py
> +            (str):
Готово

2022-04-21 10:58 UTC, NekrodNIK commented on mod/db/dbhandler.py
> +from typing import Any, Optional
Готово

2022-04-21 11:08 UTC, NekrodNIK commented on mod/controller.py
> +            (str):
Готово

2022-04-21 11:08 UTC, NekrodNIK commented on mod/protocol/mtp/worker.py
> +from typing import Any, Optional, Union
Готово

2022-04-21 11:09 UTC, NekrodNIK commented
Пулл реквест исправлен, жду повторного ревью

2022-04-21 11:37 UTC, stepanskryabin approved these changes

2022-04-21 15:01 UTC, merged