Dev improve manage #188
MoreliaTalk/morelia_server pull request #207
Opened 2022-06-06 15:42 UTC by stepanskryabin

## Synopsis
Description about main changes and how that would affected on project.

## Main changes

- a
- b
- c
- d

## Other important changes

- a
- b
- c
- d

## Self check [Running before create pull-request](https://moreliatalk.github.io/morelia_server/development.html#running-before-create-pool-request)

- [ ] I checked the code with a static analyzer `mypy`?

- [ ] I checked the code with a `flake8`?

- [ ] I checked the code with a `Unittest`?

- [ ] Have I written/corrected the documentation for the sections of code I added?

### Closes issue and bug

Closes #188 
Closes #48 
Closes #108

2022-06-08 12:05 UTC, NekrodNIK requested changes

2022-06-08 12:05 UTC, NekrodNIK commented on docs/source/index.rst
> -* `FastAPI <https://fastapi.tiangolo.com>`_ - basic framework
Забыл не просто удалить, а изменить на starlette

2022-06-08 12:05 UTC, NekrodNIK commented on mod/log_handler.py
> +config = ConfigHandler(log=False)
Я думаю, что это надо вынести в конфиг.

2022-06-08 12:07 UTC, NekrodNIK reviewed
В целом есть мелкие замечания, но... Работа проделана хорошо, респект!

2022-06-08 12:24 UTC, stepanskryabin commented on docs/source/index.rst
> -* `FastAPI <https://fastapi.tiangolo.com>`_ - basic framework
Там ниже про старлетте написано.

2022-06-08 12:24 UTC, stepanskryabin commented on mod/log_handler.py
> +config = ConfigHandler(log=False)
это строго для тестов, чтобы не срало в лог

2022-06-08 12:42 UTC, NekrodNIK commented on mod/log_handler.py
> +config = ConfigHandler(log=False)
всё что касается тестов - пишется в тестах, а не в основном коде

2022-06-08 13:40 UTC, NekrodNIK requested changes
Тесты упали

2022-06-08 13:42 UTC, stepanskryabin commented
> Тесты упали

ага, щас поправлю

2022-06-08 18:32 UTC, stepanskryabin commented
Тесты исправил, точнее закостылил. Для нормального исправления надо рефакторить много кода, а часть переделывать вовсе.

2022-06-09 04:57 UTC, NekrodNIK approved these changes

2022-06-09 04:59 UTC, merged