Переработан ConfigHandler, а также проведена работа по подготовке к релизу 0.4.0
MoreliaTalk/morelia_server pull request #209
Opened 2022-06-12 19:06 UTC by NekrodNIK

## Сhanges

- Переписан класс ConfigHandler, код значительно сокращён и упрощён
- Функционал создания бэкапов конфига и их восстановления перенесён в manage.py
- Был выполнен переход синтаксиса конфига с .ini файлов на .toml
- Настройки по умолчанию для конфига были перенесены в модели валидации(для реализации настроек по умолчанию)
- Реализована работа сервера без конфига

## Self check [Running before create pull-request](https://moreliatalk.github.io/morelia_server/development.html#running-before-create-pool-request)

- [ ] I checked the code with a static analyzer `mypy`?

- [ ] I checked the code with a `flake8`?

- [ ] I checked the code with a `Unittest`?

- [ ] Have I written/corrected the documentation for the sections of code I added?

### Closes issue and bug

Closes #...

Closes #...

2022-06-13 08:18 UTC, stepanskryabin requested changes
ПР требует глобальной доработки или смены концепции. Часть изменений не может быть принята, т.к. ведёт за собой новые зависимости на сторонние проекты.

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
> +from pathlib import PurePath, Path
неиспользуемый импорт Path

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
> +from unittest.mock import patch, Mock
неиспользуемый импорт Mock

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
> +import manage
неиспользуемый импорт

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
>  from manage import create
в 35 строке неиспользуемый импорт copy_config

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
> +        self.assertEqual(result.stdout, "".join(("Config file => deleted.\n",
Перенос.

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
> +                                  "Database file is not found => NOT deleted.\n")))
Вполне можно заменить на self.assertRegex и скоратить длинну строки.

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
> +    def test_clean_init(self, is_file_mock, remove_mock):
is_file_mock и remove_mock почему-то не используются?

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
> +    def test_error_in_clean_init(self, is_file_mock, remove_mock):
is_file_mock и remove_mock почему-то не используются?

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
> +    def test_init(self, create_table, create_admin_mock):
create_table и create_admin_mock почему-то не используются?

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
> +    def test_devserver(self, run_server_mock):
run_server_mock почему-то не используется?

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_manage.py
> +    def test_server(self, run_server_mock):
run_server_mock почему-то не используется?

2022-06-13 08:18 UTC, stepanskryabin commented on tests/test_config_validator.py
> -                          secret_key=123156)
Обоснуй почему полностью выкинул тестирование валидатора?

2022-06-13 08:18 UTC, stepanskryabin commented on example_config.ini
> -SECRET_KEY = 365fdb0a1dad5ba48518cfa63f407e9aae86b032cf34bd4a
Обосную зачем выкинул пример конфига?

2022-06-13 08:18 UTC, stepanskryabin commented on manage.py
> -    config = ConfigHandler(log=False)
Очень зря убрал настройку, теперь ConfigHandler всегда пишет лог.

2022-06-13 16:15 UTC, NekrodNIK commented on manage.py
> +import tomli_w
Используемый

2022-06-13 16:17 UTC, NekrodNIK commented on manage.py
> +        case ("register_user", ):
Исправлено

2022-06-13 16:20 UTC, NekrodNIK commented on mod/config/handler.py
> +                 filepath: PurePath | str = "config.toml") -> None:
Да. Если если путь относительный, то конфиг откроется относительно директории проекта, а если абсолютный - то откроется по данному пути. То есть, передав имя конфига, мы просто откроем его в корневой директории

2022-06-13 17:13 UTC, NekrodNIK commented on tests/test_config_handler.py
> +        self.assertEqual(value_read, fake_toml)
Да. И ещë он работал с конфиглм на диске, а это не есть хорошо

2022-06-13 17:15 UTC, NekrodNIK commented on tests/test_config_handler.py
> +    def test_get_fullpath_and_check_exist(self, is_file_mock):
Потому, что возвращаемое значение уже было указано выше, а mock в любом случае надо передать в функцию

2022-06-13 17:17 UTC, NekrodNIK commented on mod/config/models.py
> +    api: ApiModel = ApiModel()
Тогда в конфиге придëтся валить всë в одну кучу, а не раскладывать по разделам

2022-06-13 17:18 UTC, NekrodNIK commented on mod/log_handler.py
> +                   format=config_option.logging.debug,
В разы понятней стало, что за debug)))

2022-06-14 08:57 UTC, NekrodNIK commented on mod/config/handler.py
> +        return f"Config: {self._path}"
Исправлено

2022-06-14 13:43 UTC, NekrodNIK commented on mod/config/handler.py
> +        interpolation: Interpolation behaviour may be customized by providing
Исправлено

2022-06-14 13:44 UTC, NekrodNIK commented on mod/config/handler.py
> +import tomli
Возвращён старый парсер, до того времени, пока библиотека tomli не будет включена в stdlib

2022-06-14 13:46 UTC, NekrodNIK commented on mod/config/handler.py
> +class ConfigIsNotValidException(Exception):
Исправлено

2022-06-14 13:48 UTC, NekrodNIK commented on mod/config/handler.py
> +    def _get_fullpath_and_check_exist(filepath: PurePath) -> Path | None:
Исправлено

2022-06-14 13:48 UTC, stepanskryabin commented on tests/test_config_handler.py
> +    def test_get_fullpath_and_check_exist(self, is_file_mock):
тогда просто утилизируй несипользуемый объект:
```python
_ = is_file_mock
```

2022-06-14 13:53 UTC, NekrodNIK commented on tests/test_config_handler.py
> +        self.assertEqual(value_read, fake_toml)
И работал тест с конфигом на диске, что ужас. Так что все танцы с бубнами обоснованны - мы подделываем работу с файлом

2022-06-14 13:53 UTC, NekrodNIK commented on tests/test_config_handler.py
> +        self.assertEqual(value_read, fake_toml)
А сравнивается считанный конфиг с фейковым

2022-06-14 14:24 UTC, NekrodNIK commented on tests/test_config_handler.py
> +    def test_read(self, MockPath, mock_get_path):
Исправлено

2022-06-14 14:28 UTC, NekrodNIK commented on .gitignore
> -config.ini.BAK*
Исправлено

2022-06-14 14:30 UTC, NekrodNIK commented on mod/config/models.py
> +    api: ApiModel = ApiModel()
А как иначе сделать поля в конфиге необязательными? Правильно, если их нет - то подставлять дефолтные. Присвоение полям в модели валидации значений по-умолчанию решает эту проблему

2022-06-14 14:32 UTC, NekrodNIK commented on mod/config/models.py
> +    api: ApiModel = ApiModel()
2 - зато куда понятней и при доступе к ним и при чтении кофига человеком, какая опция к чему принадлежит

2022-06-14 14:33 UTC, NekrodNIK commented on mod/log_handler.py
> +                   format=config_option.logging.debug,
Так что это я менять не буду

2022-06-14 15:10 UTC, asanikushin commented on mod/log_handler.py
> +                   format=config_option.logging.debug,
> Вот пример дополнительной вложенности: было: `config_option.debug` стало: `config_option.logging.debug`

Дебаг бывает не только в логах, но и в настройках самого сервера, смотри дебаг-режим фласка. Если не брать случай автоматического релоада при изменении кода, то в проде не стоит показывать кишки 500-ошибок, в дебаге можно.

Мне кажется такое разделение оправданным

2022-06-15 04:33 UTC, NekrodNIK commented on mod/shared_lib.py
> +    db_connect = DBHandler(uri=config_option.database.url)
Исправлено

2022-06-15 04:44 UTC, NekrodNIK commented on mod/shared_lib.py
> +config_option = _config.read()
Исправлено

2022-06-15 04:48 UTC, NekrodNIK commented on tests/test_manage.py
> +from pathlib import PurePath, Path
Испрвлено

2022-06-15 04:48 UTC, NekrodNIK commented on tests/test_manage.py
> +from unittest.mock import patch, Mock
Исправлено

2022-06-15 04:48 UTC, NekrodNIK commented on tests/test_manage.py
> +import manage
Исправлено

2022-06-15 04:49 UTC, NekrodNIK commented on tests/test_manage.py
>  from manage import create
Исправлено

2022-06-15 04:50 UTC, NekrodNIK commented on tests/test_manage.py
> +        self.assertEqual(result.stdout, "".join(("Config file => deleted.\n",
Исправлено

2022-06-15 04:51 UTC, NekrodNIK commented on tests/test_manage.py
> +                                  "Database file is not found => NOT deleted.\n")))
Исправлено

2022-06-15 04:52 UTC, NekrodNIK commented on tests/test_config_validator.py
> -                          secret_key=123156)
Фактически там нечего тестировать. Всё это функционал pydantic

2022-06-15 04:52 UTC, NekrodNIK commented on example_config.ini
> -SECRET_KEY = 365fdb0a1dad5ba48518cfa63f407e9aae86b032cf34bd4a
А на кой он на сервере? Пример в доках будет

2022-06-15 04:53 UTC, NekrodNIK commented on manage.py
> -    config = ConfigHandler(log=False)
Исправлено

2022-06-15 05:24 UTC, stepanskryabin commented on mod/config/handler.py
> +                 filepath: PurePath | str = "config.toml") -> None:
Давай всё таки определимся мы имя конфига передаём или путь к нему? если путь, тогда логичнее ввести два параметра: filename и filepath.

2022-06-15 05:25 UTC, stepanskryabin commented on tests/test_config_handler.py
> +        self.assertRegex(ConfigHandler("config.toml").__str__(), "config.toml")
Согласен что с локальным файлом работать плохо, но тест стал совсем не читаемым.

2022-06-15 05:28 UTC, stepanskryabin commented on mod/config/models.py
> +    api: ApiModel = ApiModel()
Тогда обрати внимание на такой класс пидантика как [BaseSattings](https://pydantic-docs.helpmanual.io/usage/settings/)

2022-06-15 05:32 UTC, stepanskryabin commented on mod/log_handler.py
> +                   format=config_option.logging.debug,
Дополнительная вложденность никак не облегчает работу с настройками. Здесь оптимальным мне видится сменить `config_option.debug` на `config_option.LOGGING_DEBUG`. Таким образом понятно что за настройка, и нет дополнительной вложенности. А специальный класс пидантика [BaseSettings](https://pydantic-docs.helpmanual.io/usage/settings/) поможет валидировать настройки без доп вложенности.

2022-06-15 05:33 UTC, stepanskryabin commented on mod/config/models.py
> +    api: ApiModel = ApiModel()
Впринципе, используя BaseSettings можно вообще избавиться от класса ConfigHandler.

2022-06-15 05:37 UTC, stepanskryabin commented on tests/test_config_validator.py
> -                          secret_key=123156)
Не забывай, что код меняется/дополняется постоянно, в том числе и у валидатора. Самым простым вариантом проверки что всё с кодом нормально являются тесты. Пример: если ты в попытке добавления новой функциональности временно поменяешь тип данных в валидаторе, а потом забудешь вернуть обратно, то эти тесты тебе вежливо напомнять поо это.

2022-06-15 05:39 UTC, stepanskryabin commented on example_config.ini
> -SECRET_KEY = 365fdb0a1dad5ba48518cfa63f407e9aae86b032cf34bd4a
Приме нужен чтобы сразу отредактировать готовый конфиг. Это лучше чем копипастить конфиг из доков, тем более в голой консоли копипастить из доков менее удобно чем выполнить:
```cmd
cp example_config.ini config.ini
```

2022-06-15 05:41 UTC, stepanskryabin commented on mod/config/models.py
> +    api: ApiModel = ApiModel()
Вот тут пример такого подхода: https://github.com/stepanskryabin/full-stack-fastapi-postgresql/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/backend/app/app/core/config.py

2022-06-15 05:55 UTC, NekrodNIK commented on mod/config/handler.py
> +                 filepath: PurePath | str = "config.toml") -> None:
Путь. Просто путь может быть относительным

2022-06-15 05:57 UTC, NekrodNIK commented on mod/config/models.py
> +    api: ApiModel = ApiModel()
Да, натыкался как-то на BaseSettings но ниже не прочитал, что так можно. Но это уже тема для отдельного пулл реквеста

2022-06-15 05:58 UTC, NekrodNIK commented on example_config.ini
> -SECRET_KEY = 365fdb0a1dad5ba48518cfa63f407e9aae86b032cf34bd4a
Ладно, верну

2022-06-15 06:45 UTC, stepanskryabin commented on mod/config/models.py
> +    api: ApiModel = ApiModel()
Просто введя BaseSettings можно сразу решить:
1. решить проблемы с хранением дефолтных настроек и их валидацией
2. убрать дублирующие конфиги: `example_config.ini` и `config.ini`
3. сделать конфиг ридонли
4. устранить дополнительную вложенность для доступа к конфигурируемым параметрам
5. упростить тесты

2022-06-16 05:16 UTC, NekrodNIK commented
Жду повторного ревью

2022-06-19 08:57 UTC, closed without merging