Переписан класс ConfigHandler
MoreliaTalk/morelia_server pull request #217
Opened 2022-06-19 09:25 UTC by NekrodNIK

## Main changes

- Переписан класс ConfigHandler, код значительно сокращён и упрощён
- Написана прослойка для работы с ConfigParser, упрощающую работу с ним
- Настройки по умолчанию для конфига были добавлены в модель валидации
- Реализована работа сервера без конфига
- Разделены на отдельные классы валидация конфига
- Инстансы конфига и базы данных были выделены в отдельный модули в соответвующих модулях config и db
- Код, ранее запускавшийся при импортировании server.py, теперь запускается при запуске сервера starlette (был вынесен в отдельную функцию)
- Приведены в рабочее состояние тесты для manage.py
- Повышено покрытие кода

## Self check [Running before create pull-request](https://moreliatalk.github.io/morelia_server/development.html#running-before-create-pool-request)

- [ ] I checked the code with a static analyzer `mypy`?

- [ ] I checked the code with a `flake8`?

- [ ] I checked the code with a `Unittest`?

- [ ] Have I written/corrected the documentation for the sections of code I added?

### Closes issue and bug

Closes #...

Closes #...

2022-06-20 19:01 UTC, stepanskryabin requested changes

2022-06-21 08:32 UTC, NekrodNIK commented on manage.py
> +@run.command("conf_restore",
И потому что, это разные действия

2022-06-21 08:40 UTC, NekrodNIK commented on mod/config/handler.py
> +class IniParser:
ЗАЧЕМ?! Зачем необходимо включать этот функционал внутрь ConfigHandler, или превращать в две функции? Так, как реализовал я весь парсинг заключён в IniParser, и это просто отлично

2022-06-21 08:55 UTC, stepanskryabin commented on mod/config/handler.py
> +class IniParser:
`class` создаёт новый объект который объеденяет в себе данные, методы, другие класссы, что даёт ему возможность меняться в зависимости от контекста.
Функция это простой объект по обработке входящих данных (апаметров) в исходящие.

IniParser не является классом, т.к. он не создаёт разделяемого между методами области видимости, т.е. там нет данных. Оба метода являются статическими, и выполняют разный функционал, этот функционал никак не меняется. Соответственно IniParser это псевдо-класс, который по своей сути является двумя функциями.

2022-06-21 08:58 UTC, stepanskryabin commented on manage.py
> +@run.command("conf_restore",
> А как восстановить не дефолтные а?

А зачем нам восстанавливать "не дефолтные" настройки средствами нашего сервера? Опиши типовой кейс такого поведения?

2022-06-21 09:00 UTC, stepanskryabin commented on manage.py
> +@run.command("conf_restore",
> И потому что, это разные действия

а если я хочу чтобы у моих бэкап файлов в имени была дата их создания, а не просто случайные цифирки? А если я не воспринимаю арабское начертание цифр и люблю римское? надо рассмотреть все варианты кейсов!

2022-06-21 09:53 UTC, NekrodNIK commented on manage.py
> +@run.command("conf_restore",
Типовой кейс: Ты решил поиграться с настройками сервера, имея уже при этом важную тебе конфигурацию. Ты можешь сделать бэкап, а потом легко восстановить прежний конфиг

2022-06-21 09:54 UTC, NekrodNIK commented on manage.py
> +@run.command("conf_restore",
> > И потому что, это разные действия
> 
> а если я хочу чтобы у моих бэкап файлов в имени была дата их создания, а не просто случайные цифирки? А если я не воспринимаю арабское начертание цифр и люблю римское? надо рассмотреть все варианты кейсов!

Это тема для отдельно ПР, пока и так нормально

2022-06-21 09:59 UTC, NekrodNIK commented on mod/config/handler.py
> +class IniParser:
Ну да, IniParser существует лишь для удобства, что бы было понятно, чем занимаются эти 2 функции, даже не открывая документацию

2022-06-21 10:15 UTC, NekrodNIK commented on manage.py
> +DEFAULT_CONFIG = 'config.init'
Исправлено

2022-06-21 10:15 UTC, NekrodNIK commented on manage.py
> +DEFAULT_CONFIG = 'config.init'
Исправлено

2022-06-21 10:17 UTC, NekrodNIK commented on manage.py
> +              default="".join(get_default_backup_config_name()))
Исправлено

2022-06-21 10:55 UTC, NekrodNIK commented on manage.py
> +def get_default_backup_config_name() -> str:
Испрвалено

2022-06-21 10:57 UTC, NekrodNIK commented on mod/config/handler.py
> +import pydantic
Исправлено

2022-06-21 10:58 UTC, NekrodNIK commented on mod/config/handler.py
> +import configparser
Исправлено

2022-06-21 10:59 UTC, NekrodNIK commented on mod/config/handler.py
> +            logging.error(f"Config {self._path} is not valid. "
Исправлено

2022-06-21 11:04 UTC, NekrodNIK commented on tests/test_config_handler.py
> +        ConfigHandler("config.ini").backup("new_backup")
Исправлено

2022-06-21 11:14 UTC, NekrodNIK commented on server.py
> +from mod.db.instance import db_connect
Исправлено

2022-06-21 11:21 UTC, NekrodNIK commented on mod/db/instance.py
> +db_connect = DBHandler(uri=config_option.database.url)
Исправлено

2022-06-21 11:25 UTC, NekrodNIK commented on mod/config/handler.py
> +    def backup(self, backup_name: str) -> None:
Затем, что кастомные настройки надо бэкапить, если что

2022-06-21 11:26 UTC, NekrodNIK commented on mod/config/handler.py
> +            self._is_exist = True
Исправлено

2022-06-21 11:37 UTC, NekrodNIK commented on tests/test_config_handler.py
> +from unittest.mock import patch, Mock
Исправлено

2022-06-21 12:36 UTC, NekrodNIK commented
@stepanskryabin не придирайся ты уже к мелочам, прими пулл реквест

2022-06-22 11:29 UTC, merged