Добавление модульных тестов. Тесты для api.py - тестирование валидации JSON-файла
MoreliaTalk/morelia_server pull request #32
Opened 2020-08-26 18:02 UTC by stepanskryabin

Простой тест, который проверяет тип данных выдаваемых классом валидации.

2020-08-26 18:17 UTC, rus-ai requested changes
Предлагаю заменить os.getcwd() на os.path.abspath(os.path.dirname( _ _file_ _ ))
Первый вариант возвращает имя директории из которой запустили файл, а вторая директорию в которой файл лежит. При запуске python test\test.py их значения будут отличаться.

2020-08-26 18:23 UTC, rus-ai requested changes
Также конструкция TEST_FILE = '\\'.join((FIXTURES_PATH, 'api.json')) не кросплатформенная, в линуксе дробь в обратную сторону.
Нужно использовать os.path.join(FIXTURES_PATH, 'api.json')

2020-08-26 18:27 UTC, rus-ai reviewed
А для чего вот это?
`sys.path.append`

2020-08-26 18:38 UTC, stepanskryabin commented
> 
> 
> А для чего вот это?
> `sys.path.append`

Так как директория в которой запускается пайтон является директорийе поиска модулей, все модули в директориях выше пайтон не видит, таким образом через sys.path.append я добавляю директорию mod в PATH для импорта модулей которые в ней расположены.

2020-08-26 18:47 UTC, rus-ai commented
> > А для чего вот это?
> > `sys.path.append`
> 
> Так как директория в которой запускается пайтон является директорийе поиска модулей, все модули в директориях выше пайтон не видит, таким образом через sys.path.append я добавляю директорию mod в PATH для импорта модулей которые в ней расположены.

Вроде бы не рекомендованная практика, так как другие модули могут поползти, например database не найдет свою базу или шаблоны кто то свои не найдет.
Рекомендованный способ запуска все таки из корневой папки проекта `python -m TestsFolder.TestUnit`

2020-08-26 18:52 UTC, stepanskryabin commented
> 
> 
> > > А для чего вот это?
> > > `sys.path.append`
> > 
> > 
> > Так как директория в которой запускается пайтон является директорийе поиска модулей, все модули в директориях выше пайтон не видит, таким образом через sys.path.append я добавляю директорию mod в PATH для импорта модулей которые в ней расположены.
> 
> Вроде бы не рекомендованная практика, так как другие модули могут поползти, например database не найдет свою базу или шаблоны кто то свои не найдет.
> Рекомендованный способ запуска все таки из корневой папки проекта `python -m TestsFolder.TestUnit`

Для тестов нормально, так как этот импорт используется только в самом тесте. На работу сервера не влияет.

2020-08-26 19:05 UTC, rus-ai approved these changes
Approved.

Но насчет путей на будущее посмотри, возможно из-за того что не по рекомендованному способу автотестирование не сможет работать.

2020-08-26 19:06 UTC, stepanskryabin commented
> 
> 
> Approved.
> 
> Но насчет путей на будущее посмотри, возможно из-за того что не по рекомендованному способу автотестирование не сможет работать.

скоро узнаем ;)

2020-08-28 13:11 UTC, NekrodNIK approved these changes
Норм

2020-08-28 13:12 UTC, merged