Добавление модульных тестов. Тесты для controller.py - тестирование работы методов
MoreliaTalk/morelia_server pull request #34
Opened 2020-08-28 18:04 UTC by stepanskryabin

**ДИСКЛЕЙМЕР**
**По поводу оптимизации тестов: я написал соответствующий класс, он называется TestApiControllers где реализовал более интересную схему прогонки тестов. К сожалению, генерируемый результат выполнения тестов мне не понравился.**

### Изменения в controller.py:
- исправлен импорт ValidationError
- изменена функция check_uuid_and_auth_id
- оптимизирована работа функции user_info
- все текстовые ошибки заменены функцией error_catching()
- конструкция "if bool(dbquery.count()):" заменена на "if dbquery.count():".
- лишние вызовы time() удалены
- удалён неиспользуемая функция filter_dbquery_by_time_from_and_to()
- запросы к базе данных исправлены
- переработан (упрощён) алгоритм авторизации
- обновлён механизм добавления сообщений в список в методе all_message
- оптимизирована фильтрация сообщений в методе get_update, временно удалена фильтрация.
- оптимизирована генерация списка сообщений в методе get_update.
- оптимизация запросов к базе данных методом send_message
- метод add_flow переписан
- метод all_flow переписан
- Добавлена функция проверки UUID и auth_id во все методы (кроме регистрации и авторизации), а там, где я забыл добавить, потом добавить.
- исправлен запрос к базе данных в методе delete_message.
- исправлен запрос к базе данных в методе all_message
- оптимизирована работа метода errors, часть его работы перенесена в функцию serve_request().
- другие мелкие оптимизации кода, лень все описывать :)

### Изменения в models.py
- добавлено описание для столбцов таблицы

### Изменения в api.py
- в классе Flow исправлен тип для поля id 

###Изменения в test_controller.py
все тесты переписаны или оптимизированы

2020-08-31 15:57 UTC, NekrodNIK requested changes
@stepanskryabin 
Зачем удалил фильтрацию в методе get_update()?

2020-08-31 16:05 UTC, stepanskryabin commented
> 
> 
> @stepanskryabin
> Зачем удалил фильтрацию в методе get_update()?

1. нужен другой вариант, для фильтрации через SQLObject. Тот вариан что был ранее, не проходил тесты (но это не точно).
2. в самом протоколе про такой вариант фильрации нет чётких указаний, нужно сначала определиться с протоколом.

в итоге я решил тупо выпилить старую фильтрацию, чтобы потом исправив протокол было точно понятно какая фильтрация нам нужна.

2020-09-01 04:31 UTC, NekrodNIK approved these changes
OK

2020-09-01 06:18 UTC, rus-ai approved these changes
Вроде все здорово. 

Но на будущее предлагаю все таки вместо if db.count усложнить конструкции в коде и писать в лог если результате больше одной строки. По идее этого не должно случаться если добавляем в базу с проверками - но все таки проверять надо. А то мне от конструкции [0] всегда страшно становится а вдруг там и [1] есть.

2020-09-01 06:21 UTC, merged