Исправлена работа с вебсокетами, удалён легаси-код
MoreliaTalk/morelia_server pull request #54
Opened 2020-10-04 21:53 UTC by stepanskryabin

### Основные изменения в этом пулл-реквесте:
- app.py переименован  в server.py
- удалён импорт config.py
- обновлены зависимости в Pipfile и Pipfile.lock
- удалена папка "old"
- добавлен указание количества добавленных сообщений в БД
- добавлена команда "superuser" в manage.py, для создания дефолтного пользователя
- добавлен модуль "websockets" в зависимости
- удален uvicorn из импорта server.py
- включен режим "binary" в функции webocket.send_json().
- добавлено протоколирование и закрытие веб-сокета, в случае потери соединения
- добавлена обработка RuntimeError в webocket_endpoint()
- добавлен обёртка debug_server.py для запуска и тестирования сервера
- удалены неиспользуемые настройки в конфигурационном файле config.py
- прочие мелкие правки

2020-10-05 08:38 UTC, Hazzari approved these changes

2020-10-05 11:34 UTC, Hazzari approved these changes

2020-10-06 04:43 UTC, NekrodNIK requested changes
Сервер нужно запускать с отключёнными цветами, так как на некоторых устройствах они некорректно отображаются. А в остальном всё вроде нормально

2020-10-06 05:21 UTC, NekrodNIK approved these changes
OK

2020-10-06 05:23 UTC, merged