log levels
MoreliaTalk/morelia_server pull request #69
Opened 2020-10-16 13:57 UTC by Hazzari

Дополнил описание уровней логирования

2020-10-16 20:37 UTC, stepanskryabin requested changes

2020-10-16 20:37 UTC, stepanskryabin commented on settings/logging.py
> +        50 = CRITICAL -> Уровень CRITICAL
Или удали русское описание (тем паче оно с ашипками) или распиши более подробно, но на английском языке.

2020-10-16 20:59 UTC, stepanskryabin approved these changes

2020-10-21 04:07 UTC, NekrodNIK approved these changes

2020-10-21 04:07 UTC, merged